name: main

on:
  push:
    branches:
      - master
      
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Checkout dependencies
      uses: actions/checkout@v2
      with:
        repository: ${{ secrets.LibsRepository }}
        token: ${{ secrets.LibsRepositoryToken }}
        path: 3rdparty/ml

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore -c Release
      
    - name: Publish a release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          .build/Release (x64)/Modules/net472/ReMod.Core.dll
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
